#if os(macOS)
    import AppKit
    import Foundation
    import Logging

    /// Manages installation of the `ctrlx` CLI wrapper in `/usr/local/bin`.
    ///
    /// Installs a shell script that locates the CtrlX app bundle and invokes
    /// the embedded CtrlXCLI binary. This approach (used by VS Code, Sublime, etc.)
    /// avoids dynamic framework loading issues that occur with direct symlinks.
    ///
    /// Optionally also installs a zsh completion script at
    /// `/usr/local/share/zsh/site-functions/_ctrlx`, generated by invoking the
    /// bundled CtrlXCLI binary with `--generate-completion-script zsh`.
    public enum CLIInstaller {
        private static let logger = Logger(label: "com.jicezeng.ctrlx.cliinstaller")
        private static let installPath = "/usr/local/bin/ctrlx"
        private static let completionPath = "/usr/local/share/zsh/site-functions/_ctrlx"
        private static let bundleID = "com.jicezeng.ctrlx.macos"

        /// Result of an install attempt. Communicates CLI vs. completion outcomes
        /// independently so callers can surface partial successes to the user.
        public struct InstallResult: Sendable {
            public let cliInstalled: Bool
            public let completionRequested: Bool
            public let completionInstalled: Bool
            public let completionFailureReason: String?
        }

        /// Whether the CLI wrapper is installed.
        public static var isInstalled: Bool {
            FileManager.default.isExecutableFile(atPath: installPath)
        }

        /// Whether the zsh completion file is installed.
        public static var isCompletionInstalled: Bool {
            FileManager.default.fileExists(atPath: completionPath)
        }

        /// Whether the current user's login shell is zsh.
        ///
        /// macOS has defaulted to zsh since 10.15, but we still check `$SHELL`
        /// so users on bash (or anything else) don't get an irrelevant prompt.
        public static var userShellIsZsh: Bool {
            let shell = ProcessInfo.processInfo.environment["SHELL"] ?? ""
            return (shell as NSString).lastPathComponent == "zsh"
        }

        /// Install the CLI wrapper script at `/usr/local/bin/ctrlx`.
        ///
        /// When `installZshCompletion` is true, also installs the zsh completion
        /// script at `/usr/local/share/zsh/site-functions/_ctrlx`. Both files
        /// are copied in a single admin-privileges prompt.
        ///
        /// Embeds the current app bundle path directly in the wrapper script.
        @MainActor
        public static func install(installZshCompletion: Bool = false) -> InstallResult {
            guard let appPath = Bundle.main.bundlePath as String? else {
                logger.error("Could not determine app bundle path")
                return InstallResult(
                    cliInstalled: false,
                    completionRequested: installZshCompletion,
                    completionInstalled: false,
                    completionFailureReason: nil
                )
            }

            let cliPath = "\(appPath)/Contents/MacOS/CtrlXCLI"

            // Wrapper script that re-exec's into the bundled CtrlXCLI binary.
            // `escapedAppPath` is escaped for the shell single-quoted string below.
            let escapedAppPath = appPath.replacingOccurrences(of: "'", with: "'\\''")
            let wrapperScript = """
            #!/bin/bash
            # CtrlX CLI — installed by CtrlX.app
            # Re-run "Install Command Line Tool..." if you move the app.

            CLI='\(escapedAppPath)/Contents/MacOS/CtrlXCLI'
            if [ ! -x "$CLI" ]; then
                echo "Error: CtrlXCLI not found at $CLI" >&2
                echo "The app may have moved. Re-run Install Command Line Tool from the CtrlX menu." >&2
                exit 1
            fi

            exec "$CLI" "$@"
            """

            // Stage temp files inside our own sandboxed tmp directory so no path
            // with user-supplied characters ever reaches the AppleScript layer.
            let stagingDir = NSTemporaryDirectory() + "com.jicezeng.ctrlx.cliinstaller/"
            do {
                try FileManager.default.createDirectory(
                    atPath: stagingDir,
                    withIntermediateDirectories: true
                )
            } catch {
                logger.error("Failed to create staging dir: \(error)")
                return InstallResult(
                    cliInstalled: false,
                    completionRequested: installZshCompletion,
                    completionInstalled: false,
                    completionFailureReason: "Could not create staging directory"
                )
            }
            defer { try? FileManager.default.removeItem(atPath: stagingDir) }

            let wrapperTempPath = stagingDir + "ctrlx-wrapper.sh"
            do {
                try wrapperScript.write(toFile: wrapperTempPath, atomically: true, encoding: .utf8)
            } catch {
                logger.error("Failed to write wrapper script: \(error)")
                return InstallResult(
                    cliInstalled: false,
                    completionRequested: installZshCompletion,
                    completionInstalled: false,
                    completionFailureReason: nil
                )
            }

            // If requested, try to generate the completion script alongside.
            // A failure here is soft — we still install the CLI but report it
            // so the caller can tell the user completion was skipped.
            var completionTempPath: String?
            var completionFailureReason: String?
            if installZshCompletion {
                switch generateCompletionScript(cliPath: cliPath, toDirectory: stagingDir) {
                case let .success(path):
                    completionTempPath = path
                case let .failure(reason):
                    completionFailureReason = reason
                    logger.warning("Skipping zsh completion install — \(reason)")
                }
            }

            // Build the admin command. Every variable path lives inside `stagingDir`,
            // which is derived from NSTemporaryDirectory plus a fixed suffix. In
            // practice macOS's tmp path contains only hex chars and slashes, but we
            // still escape for both the shell and AppleScript string layers so a
            // pathological system short-name can't break out.
            let escapedWrapper = escapeForAppleScriptShell(wrapperTempPath)
            var adminCommand = "mkdir -p /usr/local/bin"
                + " && cp '\(escapedWrapper)' '\(installPath)'"
                + " && chmod +x '\(installPath)'"

            if let completionTempPath {
                let escapedCompletion = escapeForAppleScriptShell(completionTempPath)
                let completionDir = (completionPath as NSString).deletingLastPathComponent
                adminCommand += " && mkdir -p '\(completionDir)'"
                    + " && cp '\(escapedCompletion)' '\(completionPath)'"
                    + " && chmod 0644 '\(completionPath)'"
            }

            let script = """
            do shell script "\(adminCommand)" with administrator privileges
            """

            let appleScript = NSAppleScript(source: script)
            var error: NSDictionary?
            appleScript?.executeAndReturnError(&error)

            if let error {
                let message = error[NSAppleScript.errorMessage] as? String ?? "Unknown error"
                logger.error("Failed to install CLI: \(message)")
                // The admin command is a chained `&&` — `cp`/`chmod` for the CLI may
                // have succeeded before a later completion step failed. Re-check the
                // filesystem so we report what actually landed on disk.
                return InstallResult(
                    cliInstalled: isInstalled,
                    completionRequested: installZshCompletion,
                    completionInstalled: installZshCompletion && isCompletionInstalled,
                    completionFailureReason: completionFailureReason
                )
            }

            logger.info("CLI wrapper installed at \(installPath)")
            if completionTempPath != nil {
                logger.info("Zsh completion installed at \(completionPath)")
            }
            return InstallResult(
                cliInstalled: true,
                completionRequested: installZshCompletion,
                completionInstalled: completionTempPath != nil,
                completionFailureReason: completionFailureReason
            )
        }

        /// Remove the CLI wrapper and, if present, the zsh completion file.
        ///
        /// Skips the admin prompt entirely if neither file is installed.
        @MainActor
        public static func uninstall() -> Bool {
            var paths: [String] = []
            if isInstalled { paths.append(installPath) }
            if isCompletionInstalled { paths.append(completionPath) }

            guard !paths.isEmpty else {
                logger.info("Nothing to uninstall")
                return true
            }

            // Both paths are compile-time constants under `/usr/local/`, so no
            // shell escaping is needed beyond the single-quote wrapping.
            let quoted = paths.map { "'\($0)'" }.joined(separator: " ")
            let script = """
            do shell script "rm -f \(quoted)" with administrator privileges
            """

            let appleScript = NSAppleScript(source: script)
            var error: NSDictionary?
            appleScript?.executeAndReturnError(&error)

            if let error {
                let message = error[NSAppleScript.errorMessage] as? String ?? "Unknown error"
                logger.error("Failed to uninstall CLI: \(message)")
                return false
            }

            logger.info("CLI wrapper removed from \(installPath)")
            return true
        }

        /// Runs the bundled CtrlXCLI binary with `--generate-completion-script zsh`
        /// and writes the output to a file inside `directory`.
        private enum GenerationResult { case success(String), failure(String) }

        private static func generateCompletionScript(
            cliPath: String,
            toDirectory directory: String
        ) -> GenerationResult {
            guard FileManager.default.isExecutableFile(atPath: cliPath) else {
                return .failure("CtrlXCLI binary not found at \(cliPath)")
            }

            let process = Process()
            process.executableURL = URL(fileURLWithPath: cliPath)
            process.arguments = ["--generate-completion-script", "zsh"]
            let stdoutPipe = Pipe()
            process.standardOutput = stdoutPipe
            // Redirect stderr to /dev/null. `FileHandle(forWritingAtPath:)`
            // returns Optional, and a nil there would let the child inherit our
            // stderr — exactly the deadlock case we want to avoid. The throwing
            // URL-based initializer guarantees a non-nil handle; we surface
            // failures via termination status anyway, so dropping stderr is fine.
            let devNull: FileHandle
            do {
                devNull = try FileHandle(forWritingTo: URL(fileURLWithPath: "/dev/null"))
            } catch {
                return .failure("could not open /dev/null: \(error)")
            }
            defer { try? devNull.close() }
            process.standardError = devNull

            do {
                try process.run()
            } catch {
                return .failure("failed to launch CtrlXCLI: \(error)")
            }
            process.waitUntilExit()

            guard process.terminationStatus == 0 else {
                return .failure("CtrlXCLI exited with status \(process.terminationStatus)")
            }

            let data = stdoutPipe.fileHandleForReading.readDataToEndOfFile()
            guard !data.isEmpty, let script = String(data: data, encoding: .utf8) else {
                return .failure("empty completion script output")
            }

            let path = directory + "ctrlx-completion.zsh"
            do {
                try script.write(toFile: path, atomically: true, encoding: .utf8)
            } catch {
                return .failure("failed to write completion script: \(error)")
            }
            return .success(path)
        }

        /// Escape a path for embedding inside a single-quoted segment of a
        /// `do shell script "…"` AppleScript command.
        ///
        /// Two layers must be escaped:
        /// 1. Shell single-quoted string: `'` is closed, escaped, and reopened → `'\''`.
        /// 2. AppleScript string literal: `\` → `\\`, `"` → `\"`.
        private static func escapeForAppleScriptShell(_ path: String) -> String {
            let shellEscaped = path.replacingOccurrences(of: "'", with: "'\\''")
            return shellEscaped
                .replacingOccurrences(of: "\\", with: "\\\\")
                .replacingOccurrences(of: "\"", with: "\\\"")
        }
    }
#endif
