#!/usr/bin/env bash
#
# diagnose-tmux-freeze.sh — capture state when tmux / Claude Code freezes
# after CtrlX exits, then print a self-contained blob that can be pasted
# into a fresh chat with Claude.
#
# IMPORTANT: run this from a terminal that is NOT frozen. If the affected
# session is inside the tmux session managed by CtrlX, open a separate
# Terminal / iTerm window (outside that tmux) and run the script from there.
#
# Usage:
#   scripts/diagnose-tmux-freeze.sh [output-file]
#
# With no argument, prints to stdout. Pipe to `pbcopy` to put it on the
# clipboard, or pass an output path to write to a file.

set -u
LC_ALL=C
PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

OUT="${1:-}"
if [[ -n "$OUT" ]]; then
  exec >"$OUT"
fi

heading() {
  printf '\n========== %s ==========\n' "$1"
}

run() {
  printf '$ %s\n' "$*"
  "$@" 2>&1 || true
  printf '\n'
}

# --- preamble ---------------------------------------------------------------

cat <<'PREAMBLE'
# tmux freeze diagnostics

Generated by scripts/diagnose-tmux-freeze.sh. Paste this whole blob into a
new chat with Claude along with a one-line description of what you were
doing when the freeze hit (e.g. "ran /install mac, sleep 3 stalled forever
until I attached iTerm").

Sections:
  context       — host / OS / shell info
  ctrlx         — running CtrlX processes + state
  tmux          — tmux server / clients / sessions / pane processes
  shells        — every bash/zsh/sleep/xcodebuild/claude in `ps`
  trees         — process tree rooted at each tmux process
  power         — pmset assertions (App Nap / sleep prevention)
  lsappinfo     — Launch Services view of CtrlX
  log           — last 5 minutes of os_log for relevant processes
  lsof          — open file descriptors for CtrlX + tmux server
  samples       — 2-second `sample` stack snapshots of tmux processes

PREAMBLE

# --- context ----------------------------------------------------------------

heading "context"
date
hostname
uname -a
sw_vers 2>/dev/null
if [[ -t 0 ]]; then TTY_DESC=$(tty 2>/dev/null); else TTY_DESC="n/a"; fi
echo "user=$(whoami) uid=$(id -u) tty=$TTY_DESC shell=$SHELL"
echo "PWD=$PWD"

# Pulls a comma-separated list of PIDs matching `pgrep -x <name>`. macOS
# `ps -p` wants commas (or repeated -p), not bare whitespace.
pids_for() {
  pgrep -x "$1" 2>/dev/null | paste -sd, -
}
ps_for_pids() {
  local list="$1"
  [[ -z "$list" ]] && return
  ps -p "$list" -o pid,ppid,state,wchan,etime,command
}

# --- ctrlx ---------------------------------------------------------------

heading "ctrlx"
CTRLX_PIDS=$(pids_for CtrlX)
if [[ -z "$CTRLX_PIDS" ]]; then
  echo "(no CtrlX running)"
else
  ps_for_pids "$CTRLX_PIDS"
fi

# --- tmux processes ---------------------------------------------------------

heading "tmux"
TMUX_PIDS=$(pids_for tmux)
if [[ -z "$TMUX_PIDS" ]]; then
  echo "(no tmux running)"
else
  ps_for_pids "$TMUX_PIDS"
fi
echo
run tmux list-clients
run tmux list-sessions
run tmux list-panes -a -F '#{session_name}:#{window_index}.#{pane_index} #{pane_id} pid=#{pane_pid} cmd=#{pane_current_command} active=#{pane_active}'

# --- shells & friends -------------------------------------------------------

heading "shells"
SHELL_PIDS=""
for name in claude bash zsh sh sleep xcodebuild swift-frontend swift-driver clang ld; do
  pids=$(pids_for "$name")
  [[ -n "$pids" ]] && SHELL_PIDS+="$pids,"
done
SHELL_PIDS=${SHELL_PIDS%,}
if [[ -z "$SHELL_PIDS" ]]; then
  echo "(no matching processes)"
else
  ps_for_pids "$SHELL_PIDS"
fi

# --- process trees rooted at every tmux ------------------------------------

heading "trees"
list_descendants() {
  python3 - "$@" <<'PY'
import subprocess, sys
target = int(sys.argv[1])
out = subprocess.check_output(["ps", "-Ao", "pid,ppid,state,wchan,command"]).decode()
lines = out.splitlines()
header, rows = lines[0], lines[1:]
parent, info = {}, {}
for line in rows:
    parts = line.split(None, 4)
    if len(parts) < 5:
        continue
    pid = int(parts[0]); ppid = int(parts[1])
    parent[pid] = ppid
    info[pid] = line
print(header)
def walk(pid, depth=0):
    if pid not in info:
        return
    print("  " * depth + info[pid])
    for child, par in sorted(parent.items()):
        if par == pid:
            walk(child, depth + 1)
walk(target)
PY
}
for tpid in ${TMUX_PIDS//,/ }; do
  echo "--- descendants of tmux $tpid ---"
  list_descendants "$tpid"
done

# --- power assertions -------------------------------------------------------

heading "power"
pmset -g assertions 2>&1 | head -200

# --- lsappinfo --------------------------------------------------------------

heading "lsappinfo"
lsappinfo info -app CtrlX 2>&1 | head -60

# --- recent log entries -----------------------------------------------------

heading "log"
# Limit to processes that matter so we don't flood the output. 5 minutes is
# usually enough to capture the moment CtrlX terminated.
/usr/bin/log show --predicate \
  'process == "CtrlX" OR process == "tmux" OR process == "claude" OR process == "bash" OR process == "zsh"' \
  --info --debug --last 5m 2>&1 | tail -200

# --- lsof -------------------------------------------------------------------

heading "lsof"
for p in ${CTRLX_PIDS//,/ }; do
  echo "--- lsof ctrlx $p ---"
  lsof -p "$p" 2>&1 | head -50
done
TMUX_SVR=$(ps -Ao pid,command | awk '/[t]mux new-session/ {print $1; exit}')
if [[ -n "${TMUX_SVR:-}" ]]; then
  echo "--- lsof tmux server $TMUX_SVR ---"
  lsof -p "$TMUX_SVR" 2>&1 | head -80
fi

# --- stack samples ----------------------------------------------------------

heading "samples"
echo "Sampling tmux processes for 2s each (this will take a few seconds)..."
for tpid in ${TMUX_PIDS//,/ }; do
  echo "--- sample tmux $tpid (2s) ---"
  sample "$tpid" 2 2>&1 | sed -n '1,60p'
done
# Also sample any descendant of tmux that looks like a foreground stuck
# process — typically the user's shell or claude itself.
for tpid in ${TMUX_PIDS//,/ }; do
  for child in $(pgrep -P "$tpid" 2>/dev/null); do
    cmd=$(ps -p "$child" -o command= 2>/dev/null)
    [[ -z "$cmd" ]] && continue
    echo "--- sample child $child ($cmd) (2s) ---"
    sample "$child" 2 2>&1 | sed -n '1,60p'
  done
done

heading "done"
date
